language: go
os:
  - linux

go:
  - 1.11.x

install:
  - env GO111MODULE=on go get -u github.com/stretchr/testify
  - env GO111MODULE=on go get -u github.com/benitogf/jsondiff

script:
  - go vet ./...
  - go test -v -coverprofile cover.out -count 1 -failfast -race -bench .